import type { Book } from "@/types"

export const initialBooks: Book[] = [
  {
    id: "1",
    title: "Grande Sertão: Veredas",
    author: "João Guimarães Rosa",
    genre: "Literatura Brasileira",
    year: 1956,
    pages: 624,
    currentPage: 150,
    status: "LENDO",
    cover: "/grande-sert-o-veredas-book-cover.jpg",
    rating: 5,
    synopsis:
      "Obra-prima da literatura brasileira que narra a história de Riobaldo, um jagunço que relata suas memórias e reflexões sobre o sertão, o amor, a amizade e o pacto com o diabo.",
    notes: "Linguagem única e poética. Requer atenção na leitura.",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "2",
    title: "Cem Anos de Solidão",
    author: "Gabriel García Márquez",
    genre: "Realismo Mágico",
    year: 1967,
    pages: 432,
    currentPage: 432,
    status: "LIDO",
    cover: "/cem-anos-de-solid-o-book-cover.jpg",
    rating: 5,
    synopsis:
      "A saga da família Buendía na cidade fictícia de Macondo, misturando realidade e fantasia em uma narrativa épica sobre a América Latina.",
    notes: "Obra-prima do realismo mágico. Inesquecível.",
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    title: "Duna",
    author: "Frank Herbert",
    genre: "Ficção Científica",
    year: 1965,
    pages: 688,
    currentPage: 0,
    status: "QUERO_LER",
    cover: "/duna-book-cover-sci-fi.jpg",
    rating: 0,
    synopsis:
      "Em um futuro distante, a história segue Paul Atreides em sua jornada no planeta desértico Arrakis, único lugar onde se encontra a especiaria melange, a substância mais valiosa do universo.",
    notes: "Clássico da ficção científica. Muito recomendado.",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "4",
    title: "Sapiens: Uma Breve História da Humanidade",
    author: "Yuval Noah Harari",
    genre: "História",
    year: 2011,
    pages: 464,
    currentPage: 200,
    status: "PAUSADO",
    cover: "/sapiens-book-cover.png",
    rating: 4,
    synopsis:
      "Uma exploração fascinante da história da humanidade, desde a evolução do Homo sapiens na Idade da Pedra até as revoluções políticas e tecnológicas do século XXI.",
    notes: "Perspectiva interessante sobre a história humana.",
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "5",
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Programação",
    year: 2008,
    pages: 464,
    currentPage: 464,
    status: "LIDO",
    cover: "/clean-code-programming-book.jpg",
    rating: 5,
    synopsis:
      "Um guia essencial sobre como escrever código limpo, legível e manutenível. Apresenta princípios e práticas fundamentais para desenvolvedores de software.",
    notes: "Leitura obrigatória para programadores. Mudou minha forma de escrever código.",
    createdAt: new Date("2023-10-15"),
    updatedAt: new Date("2023-12-20"),
  },
]
