import { type Book, ReadingStatus } from "./types"

export const initialBooks: Book[] = [
  {
    id: "1",
    title: "Dom Casmurro",
    author: "Machado de Assis",
    genre: "Literatura Brasileira",
    year: 1899,
    pages: 256,
    currentPage: 256,
    rating: 5,
    synopsis:
      "Um dos maiores clássicos da literatura brasileira, Dom Casmurro narra a história de Bentinho e sua obsessão por Capitu, explorando temas como ciúme, memória e a natureza humana.",
    cover: "/placeholder-yp3gn.png",
    status: ReadingStatus.LIDO,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    title: "Dune",
    author: "Frank Herbert",
    genre: "Ficção Científica",
    year: 1965,
    pages: 688,
    currentPage: 340,
    rating: 4,
    synopsis:
      "Em um futuro distante, Paul Atreides deve navegar pela política intergaláctica e despertar poderes místicos para salvar seu povo no planeta desértico Arrakis.",
    cover: "/placeholder-7eydd.png",
    status: ReadingStatus.LENDO,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "3",
    title: "Cem Anos de Solidão",
    author: "Gabriel García Márquez",
    genre: "Realismo Mágico",
    year: 1967,
    pages: 432,
    rating: 5,
    synopsis:
      "A saga épica da família Buendía na cidade fictícia de Macondo, misturando realidade e fantasia em uma narrativa que define o realismo mágico.",
    cover: "/placeholder-r1g0e.png",
    status: ReadingStatus.QUERO_LER,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "4",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "História",
    year: 2011,
    pages: 512,
    currentPage: 512,
    rating: 4,
    synopsis:
      "Uma jornada fascinante através da história da humanidade, desde os primeiros Homo sapiens até a era moderna, explorando como nos tornamos a espécie dominante.",
    cover: "/placeholder-tm4ok.png",
    status: ReadingStatus.LIDO,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "5",
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Programação",
    year: 2008,
    pages: 464,
    currentPage: 200,
    rating: 5,
    synopsis:
      "Um guia essencial para escrever código limpo, legível e maintível. Martin compartilha princípios e práticas fundamentais para desenvolvedores.",
    cover: "/placeholder-uhuqh.png",
    status: ReadingStatus.PAUSADO,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-01"),
  },
]
